### ISSUE TITLE
Firefox won't run as root.

### ISSUE THREAD

**Issue by mluis** [entynetproject/phonia#10]
```
[i] ---- Web pages footprints ----
[*] Searching for footprints on web pages...
Traceback (most recent call last):
  File "./phonia", line 145, in <module>
    main()
  File "./phonia", line 97, in main
    scanNumber(args.phone)
  File "./phonia", line 62, in scanNumber
    osintScan(number)
  File "/home/mluis/phonia/scanners/footprints.py", line 190, in osintScan
    for result in search(req, stop=10):
  File "/home/mluis/phonia/lib/googlesearch.py", line 52, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

**Comment by enty8080** [comment]
Close your browser and run phonia.

**Comment by enty8080** [comment]
@mluis `¯\_(ツ)_/¯`

**Comment by game-lover** [comment]
I have the same problem.

**Comment by game-lover** [comment]
@mluis You can try these commands
 ```bash
pip3 install webdrivermanager
sudo webdrivermanager firefox --linkpath /usr/local/bin
```

**Comment by enty8080** [comment]
> @mluis You can try these commands
> 
> ```shell
> pip3 install webdrivermanager
> sudo webdrivermanager firefox --linkpath /usr/local/bin
> ```

Thanks, @game-lover
