### ISSUE TITLE
Invalid Argument : Can't Kill an Exited Process

### ISSUE THREAD

**Issue by rebl0x3r** [entynetproject/phonia#13]
xxx is the usa phone number, just ignore i used correctly format.

```
[*] Fetching information for 1xxx...
[*] Running local scan...
[i] International format: +1 xxx
[i] Local format: xxx
[i] Country found: United States (+1)
[i] City/Area: Michigan
[i] Carrier: 
[i] Timezone: America/New_York
[+] The number is valid and possible!
[*] Running numverify scan...
[i] Number: (+1) xxx
[i] Country: United States of America (US)
[i] Location: Richland
[i] Carrier: 
[i] Line type: landline
[!] This is most likely a landline, but it can still be a fixed VoIP number.
[*] Running OVH scan...
[*] Running custom format reconnaissance...
[i] Footprint reconnaissance for xxx
Traceback (most recent call last):
  File "./phonia", line 115, in <module>
    main()
  File "./phonia", line 75, in main
    scanNumber(args.phone)
  File "./phonia", line 39, in scanNumber
    recon.scan(number)
  File "/opt/phonia/scanners/recon.py", line 83, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/opt/phonia/lib/googlesearch.py", line 30, in search
    browser = webdriver.Firefox()
  File "/home/kodachi/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/kodachi/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/kodachi/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/kodachi/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kodachi/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

**Comment by enty8080** [comment]
@rebl0x3r reinstall WebDriver.
