### ISSUE TITLE
Problem :(

### ISSUE THREAD

**Issue by Jocanaya** [entynetproject/phonia#7]
./phonia -p +xxxxxxxxxxxx -s numverify.py
Traceback (most recent call last):
  File "./phonia", line 37, in <module>
    from lib.googlesearch import closeBrowser
  File "/data/data/com.termux/files/home/phonia/lib/googlesearch.py", line 34, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by enty8080** [comment]
RTFD, `chmod +x install.sh && ./install.sh`
